apiVersion: apps/v1
kind: Deployment
metadata:
  name: aia-cms-api-deployment
spec:
  replicas: 1  # You can adjust the number of replicas as needed
  selector:
    matchLabels:
      app: aia-cms-api
  template:
    metadata:
      labels:
        app: aia-cms-api
    spec:
      containers:
        - name: aia-cms-api
          image: acrmm01seanshared01.azurecr.io/aiaplus_cms_api:v1.0.3
          ports:
            - containerPort: 8080
          env:
            - name: ASPNETCORE_ENVIRONMENT
              value: "Uat"
