apiVersion: apps/v1
kind: Deployment
metadata:
  name: clamav-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: clamav
  template:
    metadata:
      labels:
        app: clamav
    spec:      
      containers:
        - name: clamav
          image: acrmm01seanshared01.azurecr.io/aiaplus_clamav:29102025_130024
          ports:
            - containerPort: 3310
          securityContext:
            runAsUser: 100  # matches the 'clamav' user in the base image (UID 100)     
            runAsNonRoot: true
          command: ["/init-unprivileged"] 
          
---
apiVersion: v1
kind: Service
metadata:
  name: clamav-service
spec:
  selector:
    app: clamav
  ports:
    - protocol: TCP
      port: 3310
      targetPort: 3310
  type: ClusterIP
